import lib.features.features as Features

# Trích xuất đặc trưng
def ftrExtract2(script):
    features =[]
    features.append(Features.hasLt(script))  # F1
    features.append(Features.hasScript(script))  # F2
    features.append(Features.hasAlert(script))  # F3
    features.append(Features.hasBigSmallSign2(script))  # F4
    features.append(Features.hasBigSmallSign1(script))   # F5
    features.append(Features.hasAnd(script))  # F6
    features.append(Features.hasPercentage(script))  # F7
    features.append(Features.hasSlash(script))  # F8
    features.append(Features.hasBackSlash(script))  # F9
    features.append(Features.hasPlus(script))  # F10
    features.append(Features.hasDocument(script))  # F11
    features.append(Features.hasWindow(script))  # F12
    features.append(Features.hasOnload(script))  # F13
    features.append(Features.hasOnError(script))  # F14
    features.append(Features.hasDiv(script))  # F15
    features.append(Features.hasIframe(script))  # F16
    features.append(Features.hasImg(script))  # F17
    features.append(Features.hasSRC(script))  # F18
    features.append(Features.hasVar(script))  # F19
    features.append(Features.hasEval(script))  # F20
    features.append(Features.hasHref(script))  # F21
    features.append(Features.hasCookie(script))  # F22
    features.append(Features.hasStringfromCharCode(script))  # F23
    features.append(Features.hasSingleQoute(script))  # F24
    features.append(Features.hasQuestionMark(script))  # F25
    features.append(Features.hasExclamationMark(script))  # F26
    features.append(Features.hasSemicolon(script))  # F27
    features.append(Features.hasHTTP(script))  # F28
    features.append(Features.hasJS(script))  # F29
    features.append(Features.hasHash(script))  # F30
    features.append(Features.hasEqual(script))  # F31
    features.append(Features.hasOpenBracket(script))  # F32
    features.append(Features.hasCloseBracket(script))  # F33
    features.append(Features.hasDoubleBracket(script))  # F34
    features.append(Features.hasDollar(script))  # F35
    features.append(Features.hasOpenParenthesis(script))  # F36
    features.append(Features.hasCloseParenthesis(script))  # F37
    features.append(Features.hasAsterisk(script))  # F38
    features.append(Features.hasComma(script))  # F39
    features.append(Features.hasHyphen(script))  # F40
    features.append(Features.hasLessThan(script))  # F41
    features.append(Features.hasGreaterThan(script))  # F42
    features.append(Features.hasAt(script))  # F43
    features.append(Features.hasUnderscore(script))  # F44
    features.append(Features.hasLocation(script))  # F45
    features.append(Features.hasSearch(script))  # F46
    features.append(Features.hasAndHash(script))  # F47
    features.append(Features.hasColon(script))  # F48
    features.append(Features.hasDots(script))  # F49
    features.append(Features.hasOpenBrace(script))  # F50
    features.append(Features.hasCloseBrace(script))  # F51
    features.append(Features.hasTilde(script))  # F52
    features.append(Features.hasSpace(script))  # F53
    features.append(Features.hasGrave(script))  # F54
    features.append(Features.hasDoubleEquals(script))  # F55
    features.append(Features.hasDoubleSlash(script))  # F56
    features.append(Features.hasVerticalBar(script))  # F57
    features.append(Features.hasPower(script))  # F58
    features.append(Features.lettersRatio(script))  # F59
    features.append(Features.numbersRatio(script))  # F60
    features.append(Features.symbolsRatio(script))  # F61

    return features


def ftrExtract(script, label):
    features = []
    features.append(Features.hasLt(script))  # F1
    features.append(Features.hasScript(script))  # F2
    features.append(Features.hasAlert(script))  # F3
    features.append(Features.hasBigSmallSign2(script))  # F4
    features.append(Features.hasBigSmallSign1(script))   # F5
    features.append(Features.hasAnd(script))  # F6
    features.append(Features.hasPercentage(script))  # F7
    features.append(Features.hasSlash(script))  # F8
    features.append(Features.hasBackSlash(script))  # F9
    features.append(Features.hasPlus(script))  # F10
    features.append(Features.hasDocument(script))  # F11
    features.append(Features.hasWindow(script))  # F12
    features.append(Features.hasOnload(script))  # F13
    features.append(Features.hasOnError(script))  # F14
    features.append(Features.hasDiv(script))  # F15
    features.append(Features.hasIframe(script))  # F16
    features.append(Features.hasImg(script))  # F17
    features.append(Features.hasSRC(script))  # F18
    features.append(Features.hasVar(script))  # F19
    features.append(Features.hasEval(script))  # F20
    features.append(Features.hasHref(script))  # F21
    features.append(Features.hasCookie(script))  # F22
    features.append(Features.hasStringfromCharCode(script))  # F23
    features.append(Features.hasSingleQoute(script))  # F24
    features.append(Features.hasQuestionMark(script))  # F25
    features.append(Features.hasExclamationMark(script))  # F26
    features.append(Features.hasSemicolon(script))  # F27
    features.append(Features.hasHTTP(script))  # F28
    features.append(Features.hasJS(script))  # F29
    features.append(Features.hasHash(script))  # F30
    features.append(Features.hasEqual(script))  # F31
    features.append(Features.hasOpenBracket(script))  # F32
    features.append(Features.hasCloseBracket(script))  # F33
    features.append(Features.hasDoubleBracket(script))  # F34
    features.append(Features.hasDollar(script))  # F35
    features.append(Features.hasOpenParenthesis(script))  # F36
    features.append(Features.hasCloseParenthesis(script))  # F37
    features.append(Features.hasAsterisk(script))  # F38
    features.append(Features.hasComma(script))  # F39
    features.append(Features.hasHyphen(script))  # F40
    features.append(Features.hasLessThan(script))  # F41
    features.append(Features.hasGreaterThan(script))  # F42
    features.append(Features.hasAt(script))  # F43
    features.append(Features.hasUnderscore(script))  # F44
    features.append(Features.hasLocation(script))  # F45
    features.append(Features.hasSearch(script))  # F46
    features.append(Features.hasAndHash(script))  # F47
    features.append(Features.hasColon(script))  # F48
    features.append(Features.hasDots(script))  # F49
    features.append(Features.hasOpenBrace(script))  # F50
    features.append(Features.hasCloseBrace(script))  # F51
    features.append(Features.hasTilde(script))  # F52
    features.append(Features.hasSpace(script))  # F53
    features.append(Features.hasGrave(script))  # F54
    features.append(Features.hasDoubleEquals(script))  # F55
    features.append(Features.hasDoubleSlash(script))  # F56
    features.append(Features.hasVerticalBar(script))  # F57
    features.append(Features.hasPower(script))  # F58
    features.append(Features.lettersRatio(script))  # F59
    features.append(Features.numbersRatio(script))  # F60
    features.append(Features.symbolsRatio(script))  # F61
    features.append(label)  # label

    return features
